import './js/home-page';
import './index';
import './js/saerchNews';
import './js/filter-date';
import './js/categories';
import './js/calendar';
import './js/weather';
import './js/weatherBase';
import './js/pagination';
